# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*
jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.13"]

    steps:
    - uses: actions/checkout@v5
    - name: Enable caching
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}  
      
    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Tests
      run: uv run pytest tests

    - name: Build
      run: uv build

    - name: Publish
      run: uv publish
